/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package mobi.pdf417;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static int closeButtonBackgroundNormal=0x7f040005;
        public static int closeButtonBackgroundPressed=0x7f040006;
        /**  Color of the viewfinder in default position (usually red) 
         */
        public static int default_frame=0x7f04000d;
        public static int formDetect_frame=0x7f04000c;
        public static int greendark=0x7f04000a;
        public static int greenlight=0x7f04000b;
        public static int helpButtonBackgroundDisabled=0x7f040004;
        public static int helpButtonBackgroundNormal=0x7f040002;
        public static int helpButtonBackgroundPressed=0x7f040003;
        public static int helpButtonBorder=0x7f040007;
        public static int helpButtonForeground=0x7f040008;
        /**  The color of viewfinder frame when the slip is detected on the image (usually green) 
         */
        public static int recognized_frame=0x7f04000e;
        public static int statusBackground=0x7f040000;
        public static int statusForeground=0x7f040001;
        public static int textback=0x7f040009;
    }
    public static final class drawable {
        public static int photopay_button=0x7f020000;
        public static int rounded_border=0x7f020001;
    }
    public static final class id {
        public static int backButton=0x7f060001;
        public static int scanOcr=0x7f060000;
        public static int torchButton=0x7f060002;
    }
    public static final class layout {
        public static int default_barcode_camera_overlay=0x7f030000;
    }
    public static final class string {
        public static int Copied=0x7f050013;
        public static int Copy=0x7f050011;
        public static int CustomUIForbidden=0x7f05000e;
        public static int FeatureUnsuportedAndroidVersion=0x7f050009;
        public static int FeatureUnsuportedAutofocus=0x7f050008;
        public static int FeatureUnsuportedDevice=0x7f05000a;
        public static int InvalidLicense=0x7f05000d;
        public static int LightOff=0x7f050002;
        public static int LightOn=0x7f050003;
        public static int PPCancel=0x7f05000f;
        public static int PPUse=0x7f050010;
        public static int ResultList=0x7f050012;
        public static int photopay=0x7f050000;
        public static int photopayCameraNotReady=0x7f05000c;
        public static int photopayErrorInitializing=0x7f05000b;
        public static int photopayHelpImageDescription=0x7f050006;
        public static int photopayHome=0x7f050001;
        public static int photopayOK=0x7f050005;
        /**  Error stuff UpToDate 
         */
        public static int photopayWarningTitle=0x7f050007;
        public static int scanBarcode=0x7f050004;
    }
}
