/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package mobi.pdf417;

public final class R {
    public static final class attr {
    }
    public static final class color {
        public static final int closeButtonBackgroundNormal=0x7f060005;
        public static final int closeButtonBackgroundPressed=0x7f060006;
        /**  Color of the viewfinder in default position (usually red) 
         */
        public static final int default_frame=0x7f06000d;
        public static final int formDetect_frame=0x7f06000c;
        public static final int greendark=0x7f06000a;
        public static final int greenlight=0x7f06000b;
        public static final int helpButtonBackgroundDisabled=0x7f060004;
        public static final int helpButtonBackgroundNormal=0x7f060002;
        public static final int helpButtonBackgroundPressed=0x7f060003;
        public static final int helpButtonBorder=0x7f060007;
        public static final int helpButtonForeground=0x7f060008;
        /**  The color of viewfinder frame when the slip is detected on the image (usually green) 
         */
        public static final int recognized_frame=0x7f06000e;
        public static final int statusBackground=0x7f060000;
        public static final int statusForeground=0x7f060001;
        public static final int textback=0x7f060009;
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
        public static final int photopay_button=0x7f020001;
        public static final int rounded_border=0x7f020002;
        public static final int screen=0x7f020003;
    }
    public static final class id {
        public static final int backButton=0x7f080003;
        public static final int btnBack=0x7f080000;
        public static final int btnTorch=0x7f080001;
        public static final int scanOcr=0x7f080002;
        public static final int torchButton=0x7f080004;
    }
    public static final class layout {
        public static final int camera_overlay_layout=0x7f030000;
        public static final int default_barcode_camera_overlay=0x7f030001;
    }
    public static final class raw {
        public static final int beep=0x7f050000;
    }
    public static final class string {
        public static final int Back=0x7f070014;
        public static final int Copied=0x7f070013;
        public static final int Copy=0x7f070011;
        public static final int CustomUIForbidden=0x7f07000e;
        public static final int FeatureUnsuportedAndroidVersion=0x7f070009;
        public static final int FeatureUnsuportedAutofocus=0x7f070008;
        public static final int FeatureUnsuportedDevice=0x7f07000a;
        public static final int InvalidLicense=0x7f07000d;
        public static final int LightOff=0x7f070002;
        public static final int LightOn=0x7f070003;
        public static final int PPCancel=0x7f07000f;
        public static final int PPUse=0x7f070010;
        public static final int ResultList=0x7f070012;
        public static final int app_name=0x7f070015;
        public static final int photopay=0x7f070000;
        public static final int photopayCameraNotReady=0x7f07000c;
        public static final int photopayErrorInitializing=0x7f07000b;
        public static final int photopayHelpImageDescription=0x7f070006;
        public static final int photopayHome=0x7f070001;
        public static final int photopayOK=0x7f070005;
        /**  Error stuff UpToDate 
         */
        public static final int photopayWarningTitle=0x7f070007;
        public static final int scanBarcode=0x7f070004;
    }
    public static final class xml {
        public static final int config=0x7f040000;
    }
}
